global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'impala-nodes'
    static_configs:
      - targets:
          - '10.19.20.224:9356'
          - '10.19.20.167:9356'
          - '10.19.20.149:9356'
          - '10.19.20.104:9356'
          - '10.19.20.183:9356'
          - '10.19.20.141:9356'
          - '10.19.20.45:9356'
    scrape_interval: 30s
    metrics_path: /metrics
